CREATE TABLE warps (
	id		SERIAL UNIQUE NOT NULL PRIMARY KEY,
	created		SERIAL			NOT NULL,
	server_id	SMALLSERIAL,
	warp		TEXT			NOT NULL,
	owner		SERIAL			NOT NULL,
	x		DOUBLE PRECISION	NOT NULL,
	y		DOUBLE PRECISION	NOT NULL,
	z		DOUBLE PRECISION	NOT NULL,
	yaw		DOUBLE PRECISION	NOT NULL,
	pitch		DOUBLE PRECISION	NOT NULL,
	greeting	TEXT
);

CREATE INDEX warps_lower_warp_idx ON warps (lower(warp));
