CREATE TABLE shops_history (
	id		SERIAL UNIQUE NOT NULL PRIMARY KEY,
	created		SERIAL		NOT NULL,
	server_id	SMALLSERIAL	NOT NULL,
	item_id		INTEGER		NOT NULL,
	amount		SMALLSERIAL	NOT NULL,
	price		SERIAL		NOT NULL,
	operation	BOOLEAN		NOT NULL,
	from_id		SERIAL		NOT NULL,
	to_id		SERIAL		NOT NULL,
	x		INTEGER		NOT NULL,
	y		INTEGER		NOT NULL,
	z		INTEGER		NOT NULL,
	data		INTEGER		NOT NULL
);
